from snakemake.utils import min_version
min_version("8.20")

import datetime
import re
import os
import pandas as pd

configfile: "config/config.yaml"

imd_traits = config.get('imd_traits')

# Gets script path relative to location of Snakefile given by workflow.basedir
def script_path(script):
    return os.path.join(workflow.basedir, "scripts", script)

def env_path(env):
    return os.path.join(workflow.basedir, "envs", env)

conda: env_path("global.yaml")

include: 'rules/wildcard_constraints.smk'
include: 'rules/gwas/prune_gwas_with_1kGP_data.smk'
include: 'rules/gwas/gwas.smk'
include: 'rules/gwas/phenotype_standardisation.smk'
include: 'rules/sumher.smk'
include: 'rules/ldsc.smk'
include: 'rules/gwas/iga_meta.smk'
include: 'rules/gwas/igm_meta.smk'
include: 'rules/gwas/igg_meta.smk'

include: 'rules/python/export.py'

module kGP_pipeline:
    snakefile: github("twillis209/1kGP_pipeline", path = "workflow/Snakefile", branch = 'conda')
    config: config['1kGP_pipeline']

use rule * from kGP_pipeline as kGP_*
