GWAS_tools:
  extraneous_columns: ["af_cases_meta_hq" , "af_controls_meta_hq", "beta_meta_hq", "se_meta_hq", "pval_meta_hq", "pval_heterogeneity_hq", "af_cases_meta", "af_controls_meta", "beta_meta", "se_meta", "pval_meta", "pval_heterogeneity", "af_cases_AFR", "af_cases_AMR", "af_cases_CSA", "af_cases_EAS", "af_cases_EUR", "af_cases_MID", "af_controls_AFR", "af_controls_AMR", "af_controls_CSA", "af_controls_EAS", "af_controls_EUR", "af_controls_MID", "beta_AFR", "beta_AMR", "beta_CSA", "beta_EAS", "beta_MID", "se_AFR", "se_AMR", "se_CSA", "se_EAS", "se_MID", "pval_AFR", "pval_AMR", "pval_CSA", "pval_EAS", "pval_MID", "low_confidence_AFR", "low_confidence_AMR", "low_confidence_CSA", "low_confidence_EAS", "low_confidence_EUR", "low_confidence_MID", "nearest_genes", "neglog10_pval_meta_hq", "neglog10_pval_heterogeneity_hq", "neglog10_pval_meta", "neglog10_pval_heterogeneity", "neglog10_pval_AFR", "neglog10_pval_CSA", "neglog10_pval_EAS"]
  snps_to_retain: ['17:16991599:A:G', '17:16948873:G:A', '17:17045897:A:C', '17:17262322:T:G']
  igad:
    # NB: we believe these are mislabelled hence effect -> REF rather than ALT as would be typical
    ref: "^effect_allele$"
    alt: "^other_allele$"
    extraneous_columns: ["hm_variant_id", "hm_rsid", "hm_chrom", "hm_pos", "hm_beta", "hm_ci_lower", "hm_ci_upper", "hm_effect_allele_frequency", "hm_code", "ci_lower", "ci_upper", "beta", "standard_error", "effect_allele_frequency"]
  bronson-uncorrected:
    alt: "^effect_allele$"
    ref: "^other_allele$"
    extraneous_columns: ["hm_variant_id", "hm_rsid", "hm_chrom", "hm_pos", "hm_beta", "hm_ci_lower", "hm_ci_upper", "hm_effect_allele_frequency", "hm_code", "ci_lower", "ci_upper", "beta", "standard_error", "effect_allele_frequency"]
  jia:
    ref: "^alleleA$"
    alt: "^alleleB$"
  lada:
    ref: "^reference_allele$"
    alt: "^other_allele$"
    # TODO not sure about this scz assigment; A1 is the 'reference allele for freq, beta, or ln(OR)', A2 the 'alt\', but the beta is 'of A1'
  scz:
    ref: "^A1$"
    alt: "^A2$"
  pah:
    extraneous_columns: ['chr:pos(hg19)', 'OR_se', 'OR_95L', 'OR_95U', 'p.value', 'X_.log10_p.value', 'q_statistic', 'q_p.value', 'i2']
    ref: 'other_allele'
    alt: 'effect_allele'
  1kGP_pipeline:
    sha256:
      hg19:
        chr1: "d259ae8ba408048e9b793dd70970fde5d426e8f165464d5e6bdee7963f27c4b9"
        chr2: "537f740d03c872933310523d8b06e896ef166b70d546b2cfeab1ceee0bc566dd"
        chr3: "8ad55cd4e47512c365431a36274f94ec5a6df0db6bf2e1a9b865692eb8c3270d"
        chr4: "630228658cebc54f82716b9df511ee418ead88010487695d24553340ee8d950b"
        chr5: "3b9341901d5aa42bc15c6cc87d683dac4f1e1591dd82a4bb7c78c5081ef85227"
        chr6: "f54a80c00fbfbe3e89a9e877d382e4f8afad4911597ad79bdcaa9db51f44c983"
        chr7: "f67f9531b34b278a25a450216bc2609251bbe15d91cc0a4b67dcb02e110631f8"
        chr8: "55e2ff63b4e67b816d4584f7f9775714beff63c6bf3bb3e614ed9402044ea4e8"
        chr9: "ada97534be62e5153822257bc17c2436eed16c3494c8e83bc7cd8be690b2afc1"
        chr10: "b3d73ae3e6c3999ddc1fba4bf4322e07bdc225b54f5d4603eabc9f67ec10ff54"
        chr11: "64b9f63f6d3b5056f60cb297016d9da169e0668083620e4819c934259cd5b6d1"
        chr12: "05845d1e5b8720a27298ddebaf76234744d308916d97f54355cf98a1f9962fc5"
        chr13: "564ebefc96e4b5c795979eebc81d57aca11b1b61ddec8085772864e227824f8d"
        chr14: "e39a17eb5004440697f27678c8a67b80054d880bb20a58ccde341cb34a4b7378"
        chr15: "79c35fdbc2eb00ef8220c7825283851e2aed14a56704b5f9c7f9156f99e96ef0"
        chr16: "9c021e589e619c77d0efdfb3ad9bf89752d32cd9b3916d2efb88168dbeef6284"
        chr17: "dd7082883b50aac8126c6e9864158cd875c5a60780f1bff700ce9cb85d0383c1"
        chr18: "820017d0708a8beb856c997470ba06bd9e39e886b3818a6f398a6e6159cd1c2c"
        chr19: "26683a440906e6a789636ccff4b039e923a5c7d31bde50351a760e494c1bf0c3"
        chr20: "1bbddc1eac3b35d9408bdfb435632126614a7ac89d32d27aa30db6dc94600fec"
        chr21: "1942e0709625d77928b191e5a1bfbf523aad2fee1764994a599ae4623305cace"
        chr22: "a90c16c4ff2b3196476d506ae13cb3047fae8670163c7c932c4b0239aef3daf5"
        chrX: "29ee72373faf78030d82779924e6d8f209d6ebd668ab7346c8b46675feb34d3d"
      hg38:
        chr1: "61511147295e32b55b4db8e800d12ad4aed68d458d3e4c301660f1594db07d1b"
        chr2: "250ddbfa12d27583f2db883e980f3a4df74a9d802084278ce28c6338b75ecbfc"
        chr3: "098550136d38d922154dac676297f8622f58e92ea1c0ea9cc5f60925436d32aa"
        chr4: "e814e49388623b2e2b69bfb95ce9b67e9da7c78911f85ca86f403ce7d528eb73"
        chr5: "810059e7986b0d62a9c335ad6661b58b0023b0b0d54a26731ba202c9c883a937"
        chr6: "e62c07e30600258cd508bbf7d041d4bf8710e517dc0a61b009bfce54b3372776"
        chr7: "0c61fbddfacf8897ae361daad43d992d557b846be6d3659fcda1ca7969b0b6a2"
        chr8: "7edb69aa77dc6d2a2ecb68a4f37999b11e2da3cd68d43812bece0ae9a9bd9f31"
        chr9: "6fc141568b9b9e40b12cda17da2964765b4335095094e864ef2991fe31fbb04e"
        chr10: "8afd2ce5a688b80e2093cf15986fe8df594d35348e81fa4ff2f260ae0883a52f"
        chr11: "4449e17a9eaea9d8c423d3a9fc223178848ece491a9f30a3bd451bedda784d64"
        chr12: "ea2ea1861bf05fc7f3fb68567736b8194932a69d6cb5b731123ad01353be0bed"
        chr13: "3cd298d9cf7fd7fd63e1fe28686f0373c022fcacabe9fc4fb476dfe5f2729813"
        chr14: "097576cdeb6d22188af2581b797517557825258cc10c0b7dc2aeb0be9a3d936b"
        chr15: "8a140e8b417a2de1afbf70efcd5cd7c5179ff6e8fce061d9f4eec8fcf8749ebc"
        chr16: "d7a8b7521ca5361877f63ce6dcef0d734a53679fbd13fbccf61858f3c91c7883"
        chr17: "f0f8604eb41a8f12ce6618884a410089ff6dfcce061da7417c346b223431e1ca"
        chr18: "760a465f13368d6a265a9aeddfa41c13ceacaf855a5b9572ab14574b9b059a75"
        chr19: "b8ef1404de502ed94bcd61c82a1fb0b5ed7d1462b4ac185198c6c5e0c91ae68d"
        chr20: "c2624c726c6cb27e288fe5908621125740379a3d523299dd07c13abf97645e4b"
        chr21: "574209ba9edbfda028651e631041e67bdf340fdd2d19d655c38ea3fff0287a25"
        chr22: "70ff24cfd01eab24c6f4c6e825f55a2b3475ff595f6e12e179c4ef06b9cc4df6"
        chrX: "f42c786cba67ff74c30e9bd37254b5a605a5957cfe3a5dc54e7dd41d9c9d8edc"
igad:
  novel_gwas: ['TNFAIP3', 'CD86', 'GATA3', 'FAS']
  novel_cfdr: ['RUNX3', 'ID2', 'CD247', 'PTPN2', 'ADO|EGR2', 'ADAD1|KIAA1109|IL2', 'LBH|LCLAT1', 'FCRL3', 'DUSP22|IRF4', 'ZBTB10', 'IL2RA', 'SH2B3', 'GSDMB|IKZF3', 'CCN4', 'ALDH2|PTPN11', 'RAB5B|IKZF4', 'ZFP36L1|RAD51B', 'PTPN11|RPL6']
  top_gene_to_chosen_gene: {"FAP": "IFIH1", "ALDH2": "PTPN11", "RUNX3": "RUNX3", "TNFAIP3": "TNFAIP3", "CD247": "CD247", "GATA3": "GATA3", "PTPN2": "PTPN2", "IFIH1": "IFIH1", "FAS": "FAS", "AHI1": "AHI1", "FCRL3": "FCRL3", "SH2B3": "SH2B3", "CLEC16A": "CLEC16A", "ID2": "ID2", "GSDMB": "IKZF3", "KIAA1109": "IL2", "IL2RA": "IL2RA", "CSTPP1": "AMBRA1", "CCN4": "CCN4", "ADO": "EGR2", "MYC": "MYC", "RAB5B": "SUOX", "ZFP36L1": "RAD51B", "LBH": "LCLAT1", "DUSP22": "IRF4", "ZBTB10": "ZBTB10", "CD86": "CD86"}
  iei_genes: ['TNFAIP3', 'IL2RA', 'CD247', 'IRF4', 'GSDMB|IKZF3', 'PTPN2', 'FAS']
  lead_snps:
    rs11066320:
      gene: "PTPN11"
      location: "intron"
    rs11249215:
      gene: "RP11-84D1.2"
      location: "exon"
    rs112920346:
      gene: "RP11-356I2.4|WAKMAR2"
      location: "intron"
    rs1214598:
      gene: "CD247"
      location: "intron"
    rs1244181:
      gene: "GATA3"
      location: "intron"
    rs12955302:
      gene: "PTPN2"
      location: "intron"
    rs1990760:
      gene: "IFIH1"
      location: "exon"
    rs2179781:
      gene: "AHI1"
      location: "exon"
    rs2210913:
      gene: "FCRL3"
      location: "intron"
    rs3184504:
      gene: "SH2B3"
      location: "exon"
    rs34443974:
      gene: "CLEC16A"
      location: "intron"
    rs391936:
      gene: "LINC00299"
      location: "intron"
    rs4795400:
      gene: "GSDMB"
      location: "intron"
    rs56267605:
      gene: ""
      location: "intergenic"
    rs61839660:
      gene: "IL2RA"
      location: "intron"
    rs61882719:
      gene: "AMBRA1"
      location: "intron"
    rs7005834:
      gene: "CCN4"
      location: "intron"
    rs7088066:
      gene: "EGR2"
      location: "intron"
    rs72722767:
      gene: ""
      location: "intergenic|regulatory_region"
    rs773125:
      gene: "SUOX"
      location: "intron"
    rs8015139:
      gene: "RAD51B"
      location: "intron"
    rs829689:
      gene: ""
      location: "intergenic"
    rs9391997:
      gene: "IRF4"
      location: "exon|3_prime_utr"
    rs9632837:
      gene: ""
      location: "intergenic"
    rs9831894:
      gene: "CD86"
      location: "intron"
# NB: some redundancy here to cover alternative names for known loci
known_igad_gwas_loci: ['IFIH1|FAP', 'AHI1', 'CLEC16A', 'PVT1|MYC', 'CSTPP1|DGKZ|AMBRA1|ATG13']
iga:
  known_iga_gwas_loci: ["ANKRD55", "IL6ST", "ASCC2|MTMR3", "ATP5PBP6|FILNC1", "CITED2", "CTF1", "DYSF|RPS20P10", "ELL2", "FADS1|FADS2", "GALNT12|NME2P3", "GPATCH2", "HDAC7", "HORMAD2|LIF", "IL1R1", "LINC02655|RPS7P9", "LITAF", "OVOL1|RELA", "POU2AF1", "RUNX2", "RUNX3", "RUNX3|MIR4425", "SH2B3", "ATXN2", "TMEM258", "TNFSF13", "TNFSF15", "TNFSF4|TNFSF18", "TNFSF8", "TRAF3", "ZP3|SSC4D"]
  all: ["RUNX3", "FCGR2B", "TNFSF4", "INAVA", "FADS2", "EFEMP2", "POU2AF1", "HDAC7", "SH2B3", "TRAF3", "LITAF", "CFAP119", "TNFSF13", "TNFRSF13B", "SANBR", "IL1R2", "UQCR10", "ANKRD55", "ELL2", "RUNX2", "PRDM1", "CITED2", "IKZF1", "DTX2", "IRF5", "TNFSF8"]
  novel: ["FCGR2B", "TNFRSF13B|NT5M", "INAVA", "SANBR", "PRDM1", "IKZF1", "IRF5", "TNFSF12|TNFSF13"]
  # Novel and non-novel alike
  iei_genes: ['IL6ST', 'FCGR2B|FCGR3A', "TNFRSF13B", 'POU2AF1', 'TRAF3', 'IKZF1', 'TNFSF13']
  loci:
    RUNX3:
        seqname: 1
        index_snp: "1:24972350:C:T"
        flank: "300kb"
    FCGR2B:
        seqname: 1
        index_snp: "1:161500252:T:C"
        flank: "300kb"
    TNFSF4:
        seqname: 1
        index_snp: "1:173190377:T:C"
        flank: "300kb"
    INAVA:
        seqname: 1
        index_snp: "1:200912467:G:A"
        flank: "300kb"
    FADS2:
        seqname: 11
        index_snp: "11:61828092:C:T"
        flank: "300kb"
    EFEMP2:
        seqname: 11
        index_snp: "11:65784486:A:G"
        flank: "300kb"
    POU2AF1:
        seqname: 11
        index_snp: "11:111396669:T:C"
        flank: "300kb"
    HDAC7:
        seqname: 12
        index_snp: "12:47821042:G:A"
        flank: "300kb"
    SH2B3:
        seqname: 12
        index_snp: "12:111494996:C:T"
        flank: "300kb"
    TRAF3:
        seqname: 14
        index_snp: "14:102772597:C:G"
        flank: "300kb"
    LITAF:
        seqname: 16
        index_snp: "16:11623976:T:A"
        flank: "300kb"
    CFAP119:
        seqname: 16
        index_snp: "16:30904808:G:A"
        flank: "300kb"
    TNFSF13:
        seqname: 17
        index_snp: "17:7559652:A:G"
        flank: "300kb"
    NT5M:
        seqname: 17
        index_snp: "17:16938289:G:C"
        flank: "300kb"
    SANBR:
        seqname: 2
        index_snp: "2:60939899:A:G"
        flank: "300kb"
    IL1R2:
        seqname: 2
        index_snp: "2:102072571:C:T"
        flank: "300kb"
    UQCR10:
        seqname: 22
        index_snp: "22:30185871:A:T"
        flank: "500kb"
    ANKRD55:
        seqname: 5
        index_snp: "5:56142753:C:A"
        flank: "300kb"
    ELL2:
        seqname: 5
        index_snp: "5:95941851:A:G"
        flank: "300kb"
    BTN3A2:
        seqname: 6
        index_snp: "6:26873086:T:G"
        flank: "300kb"
    ZSCAN26:
        seqname: 6
        index_snp: "6:28689681:A:G"
        flank: "300kb"
    HLA-G:
        seqname: 6
        index_snp: "6:29973407:C:T"
        flank: "300kb"
    CCHCR1:
        seqname: 6
        index_snp: "6:31139116:A:G"
        flank: "300kb"
    HLA-DRB5:
        seqname: 6
        index_snp: "6:32464779:C:T"
        flank: "300kb"
    RUNX2:
        seqname: 6
        index_snp: "6:45558952:C:T"
        flank: "300kb"
    PRDM1:
        seqname: 6
        index_snp: "6:106219660:T:G"
        flank: "300kb"
    CITED2:
        seqname: 6
        index_snp: "6:139654806:T:C"
        flank: "300kb"
    IKZF1:
        seqname: 7
        index_snp: "7:50268931:C:T"
        flank: "300kb"
    DTX2:
        seqname: 7
        index_snp: "7:76408836:A:T"
        flank: "300kb"
    IRF5:
        seqname: 7
        index_snp: "7:128939612:G:A"
        flank: "300kb"
    TNFSF8:
        seqname: 9
        index_snp: "9:114930602:C:T"
        flank: "300kb"
igad_paper:
  imd_traits: ["asthma-ex", "hyperpara", "hypothy", "derm-ecz", "pbc", "addi", "psc", "ra", "jia", "sle", "crohns", "t1d", "ms", "uc-delange", "liu-decode-lyons-dennis-iga", "igan"]
  imd_trait_efo_codes:
    asthma-ex: "MONDO_0004979"
    # NB: No GWS associations
    hyperpara: "EFO_0008506"
    hypothy: "EFO_0004705"
    derm-ecz: "EFO_0000274" # Going for 'atopic dermatitis'
    pbc: "EFO_1001486"
    addi: "Orphanet_101960" # 'genetic chronic primary adrenal insufficiency'
    psc: "EFO_0004268"
    ra: "EFO_0000685"
    jia: "EFO_0002609"
    sle: "MONDO_0007915"
    crohns: "EFO_0000384"
    t1d: "MONDO_0005147"
    ms: "MONDO_0005301"
    uc-delange: "EFO_0000729"
    liu-decode-lyons-dennis-iga: "EFO_0004912"
    igan: "EFO_0004194"
    # NB: Does not work with gwasrapidd
  infection_trait_efo_code: "EFO_0005741"
  bmi_trait_efo_code: "EFO_0004340"
  educational_attainment_trait_efo_code: "EFO_0011015"
  # NB: asthma-ex was not significant
  imd_traits_rg_with_igad: ["asthma-ex", "hypothy", "pbc", "addi", "ra", "jia", "crohns", "t1d", "uc-delange", "liu-decode-lyons-dennis-iga", "igan"]
  iga_gwas: ['liu-decode-iga', 'iga', 'dennis-iga']
  igad_loci:
      IFIH1:
        seqname: 2
        flank: '300kb'
        index_snp: '2:162267541:C:T'
      CD86:
        seqname: 3
        flank: '300kb'
        index_snp: '3:122081640:A:C'
      AHI1:
        seqname: 6
        flank: '600kb'
        index_snp: '6:135398362:C:A'
      TNFAIP3:
        seqname: 6
        flank: '300kb'
        index_snp: '6:137833918:C:T'
      MYC:
        seqname: 8
        flank: '300kb'
        index_snp: '8:128192857:G:A'
      GATA3:
        seqname: 10
        flank: '800kb'
        index_snp: '10:8049414:A:G'
      FAS:
        seqname: 10
        flank: '300kb'
        index_snp: '10:89007167:C:T'
      AMBRA1:
        seqname: 11
        flank: '300kb'
        index_snp: '11:46517392:A:G'
        locus_aliases: ['CSTPP1']
      CLEC16A:
        seqname: 16
        flank: '300kb'
        index_snp: '16:11085448:C:T'
  cfdr_loci:
      RUNX3:
        seqname: 1
        flank: '800kb'
        index_snp: '1:24970693:G:A'
      FCRL3:
        seqname: 1
        flank: '100kb'
        index_snp: '1:157699203:C:T'
      CD247:
        seqname: 1
        flank: '800kb'
        index_snp: '1:167457187:G:A'
      ID2:
        seqname: 2
        flank: '800kb'
        index_snp: '2:8304365:C:G'
      LCLAT1:
        seqname: 2
        flank: '800kb'
        index_snp: '2:30438850:A:G'
        locus_aliases: ['LBH']
      IL2:
        seqname: 4
        flank: '800kb'
        index_snp: '4:122441954:A:C'
        locus_aliases: ['KIAA1109', 'IL2RA']
      IRF4:
        seqname: 6
        flank: '800kb'
        index_snp: '6:409119:A:G'
        locus_aliases: ['DUSP22']
      ZBTB10:
        seqname: 8
        flank: '800kb'
        index_snp: '8:80405890:C:G'
      CCN4:
        seqname: 8
        flank: '100kb'
        index_snp: '8:133201961:C:T'
      IL2RA:
        seqname: 10
        flank: '800kb'
        index_snp: '10:6052734:C:T'
      EGR2:
        seqname: 10
        flank: '100kb'
        index_snp: '10:62846097:G:C'
        locus_aliases: ['ADO']
      SUOX:
        seqname: 12
        flank: '500kb'
        index_snp: '12:56001170:A:G'
        locus_aliases: ['RAB5B']
      SH2B3:
        seqname: 12
        flank: '1500kb'
        index_snp: '12:111446804:T:C'
      PTPN11:
        seqname: 12
        flank: '800kb'
        index_snp: '12:112468611:A:G'
        locus_aliases: ['ALDH2']
      RAD51B:
        seqname: 14
        flank: '800kb'
        index_snp: '14:68272584:G:T'
      IKZF3:
        seqname: 17
        flank: '800kb'
        index_snp: '17:39910767:C:T'
      PTPN2:
        seqname: 18
        flank: '300kb'
        index_snp: '18:12864763:A:G'
  iga_loci:
    RUNX3:
        seqname: 1
        index_snp: "1:24972350:C:T"
        flank: "150kb"
    SYF2:
        seqname: 1
        index_snp: "1:25167265:G:C"
        flank: "150kb"
    FCGR2B:
        seqname: 1
        index_snp: "1:161500252:T:C"
        flank: "300kb"
    TNFSF4:
        seqname: 1
        index_snp: "1:173190377:T:C"
        flank: "300kb"
    INAVA:
        seqname: 1
        index_snp: "1:200912467:G:A"
        flank: "300kb"
    FADS2:
        seqname: 11
        index_snp: "11:61828092:C:T"
        flank: "300kb"
    EFEMP2:
        seqname: 11
        index_snp: "11:65784486:A:G"
        flank: "300kb"
    POU2AF1:
        seqname: 11
        index_snp: "11:111396669:T:C"
        flank: "300kb"
    HDAC7:
        seqname: 12
        index_snp: "12:47821042:G:A"
        flank: "300kb"
    SH2B3:
        seqname: 12
        index_snp: "12:111494996:C:T"
        flank: "300kb"
    TRAF3:
        seqname: 14
        index_snp: "14:102772597:C:G"
        index_snp: "17:16938289:G:C"
        flank: "300kb"
    SANBR:
        seqname: 2
        index_snp: "2:60939899:A:G"
        flank: "300kb"
    IL1R2:
        seqname: 2
        index_snp: "2:102072571:C:T"
        flank: "300kb"
    UQCR10:
        seqname: 22
        index_snp: "22:30185871:A:T"
        flank: "500kb"
    ANKRD55:
        seqname: 5
        index_snp: "5:56142753:C:A"
        flank: "300kb"
    ELL2:
        seqname: 5
        index_snp: "5:95941851:A:G"
        flank: "300kb"
    RUNX2:
        seqname: 6
        index_snp: "6:45558952:C:T"
        flank: "300kb"
    PRDM1:
        seqname: 6
        index_snp: "6:106219660:T:G"
        flank: "300kb"
    CITED2:
        seqname: 6
        index_snp: "6:139654806:T:C"
        flank: "300kb"
    IKZF1:
        seqname: 7
        index_snp: "7:50268931:C:T"
        flank: "300kb"
    DTX2:
        seqname: 7
        index_snp: "7:76408836:A:T"
        flank: "300kb"
    IRF5:
        seqname: 7
        index_snp: "7:128939612:G:A"
        flank: "300kb"
    TNFSF8:
        seqname: 9
        index_snp: "9:114930602:C:T"
        flank: "300kb"
    TNFSF13:
        seqname: 17
        index_snp: "17:7559652:A:G"
        flank: "300kb"
    TNFRSF13B:
        seqname: 17
        index_snp: "17:16938289:G:C"
        flank: "300kb"
