ebispot_harmoniser:
  version: 1.1.10
LDlink:
  token: "9ee21d1a12e9"
1kGP_pipeline:
  sha256:
    hg19:
      chr1: "d259ae8ba408048e9b793dd70970fde5d426e8f165464d5e6bdee7963f27c4b9"
      chr2: "537f740d03c872933310523d8b06e896ef166b70d546b2cfeab1ceee0bc566dd"
      chr3: "8ad55cd4e47512c365431a36274f94ec5a6df0db6bf2e1a9b865692eb8c3270d"
      chr4: "630228658cebc54f82716b9df511ee418ead88010487695d24553340ee8d950b"
      chr5: "3b9341901d5aa42bc15c6cc87d683dac4f1e1591dd82a4bb7c78c5081ef85227"
      chr6: "f54a80c00fbfbe3e89a9e877d382e4f8afad4911597ad79bdcaa9db51f44c983"
      chr7: "f67f9531b34b278a25a450216bc2609251bbe15d91cc0a4b67dcb02e110631f8"
      chr8: "55e2ff63b4e67b816d4584f7f9775714beff63c6bf3bb3e614ed9402044ea4e8"
      chr9: "ada97534be62e5153822257bc17c2436eed16c3494c8e83bc7cd8be690b2afc1"
      chr10: "b3d73ae3e6c3999ddc1fba4bf4322e07bdc225b54f5d4603eabc9f67ec10ff54"
      chr11: "64b9f63f6d3b5056f60cb297016d9da169e0668083620e4819c934259cd5b6d1"
      chr12: "05845d1e5b8720a27298ddebaf76234744d308916d97f54355cf98a1f9962fc5"
      chr13: "564ebefc96e4b5c795979eebc81d57aca11b1b61ddec8085772864e227824f8d"
      chr14: "e39a17eb5004440697f27678c8a67b80054d880bb20a58ccde341cb34a4b7378"
      chr15: "79c35fdbc2eb00ef8220c7825283851e2aed14a56704b5f9c7f9156f99e96ef0"
      chr16: "9c021e589e619c77d0efdfb3ad9bf89752d32cd9b3916d2efb88168dbeef6284"
      chr17: "dd7082883b50aac8126c6e9864158cd875c5a60780f1bff700ce9cb85d0383c1"
      chr18: "820017d0708a8beb856c997470ba06bd9e39e886b3818a6f398a6e6159cd1c2c"
      chr19: "26683a440906e6a789636ccff4b039e923a5c7d31bde50351a760e494c1bf0c3"
      chr20: "1bbddc1eac3b35d9408bdfb435632126614a7ac89d32d27aa30db6dc94600fec"
      chr21: "1942e0709625d77928b191e5a1bfbf523aad2fee1764994a599ae4623305cace"
      chr22: "a90c16c4ff2b3196476d506ae13cb3047fae8670163c7c932c4b0239aef3daf5"
      chrX: "29ee72373faf78030d82779924e6d8f209d6ebd668ab7346c8b46675feb34d3d"
    hg38:
      chr1: "61511147295e32b55b4db8e800d12ad4aed68d458d3e4c301660f1594db07d1b"
      chr2: "250ddbfa12d27583f2db883e980f3a4df74a9d802084278ce28c6338b75ecbfc"
      chr3: "098550136d38d922154dac676297f8622f58e92ea1c0ea9cc5f60925436d32aa"
      chr4: "e814e49388623b2e2b69bfb95ce9b67e9da7c78911f85ca86f403ce7d528eb73"
      chr5: "810059e7986b0d62a9c335ad6661b58b0023b0b0d54a26731ba202c9c883a937"
      chr6: "e62c07e30600258cd508bbf7d041d4bf8710e517dc0a61b009bfce54b3372776"
      chr7: "0c61fbddfacf8897ae361daad43d992d557b846be6d3659fcda1ca7969b0b6a2"
      chr8: "7edb69aa77dc6d2a2ecb68a4f37999b11e2da3cd68d43812bece0ae9a9bd9f31"
      chr9: "6fc141568b9b9e40b12cda17da2964765b4335095094e864ef2991fe31fbb04e"
      chr10: "8afd2ce5a688b80e2093cf15986fe8df594d35348e81fa4ff2f260ae0883a52f"
      chr11: "4449e17a9eaea9d8c423d3a9fc223178848ece491a9f30a3bd451bedda784d64"
      chr12: "ea2ea1861bf05fc7f3fb68567736b8194932a69d6cb5b731123ad01353be0bed"
      chr13: "3cd298d9cf7fd7fd63e1fe28686f0373c022fcacabe9fc4fb476dfe5f2729813"
      chr14: "097576cdeb6d22188af2581b797517557825258cc10c0b7dc2aeb0be9a3d936b"
      chr15: "8a140e8b417a2de1afbf70efcd5cd7c5179ff6e8fce061d9f4eec8fcf8749ebc"
      chr16: "d7a8b7521ca5361877f63ce6dcef0d734a53679fbd13fbccf61858f3c91c7883"
      chr17: "f0f8604eb41a8f12ce6618884a410089ff6dfcce061da7417c346b223431e1ca"
      chr18: "760a465f13368d6a265a9aeddfa41c13ceacaf855a5b9572ab14574b9b059a75"
      chr19: "b8ef1404de502ed94bcd61c82a1fb0b5ed7d1462b4ac185198c6c5e0c91ae68d"
      chr20: "c2624c726c6cb27e288fe5908621125740379a3d523299dd07c13abf97645e4b"
      chr21: "574209ba9edbfda028651e631041e67bdf340fdd2d19d655c38ea3fff0287a25"
      chr22: "70ff24cfd01eab24c6f4c6e825f55a2b3475ff595f6e12e179c4ef06b9cc4df6"
      chrX: "f42c786cba67ff74c30e9bd37254b5a605a5957cfe3a5dc54e7dd41d9c9d8edc"
# sumstats cols produced by EBISPOT harmoniser
chr_col: 'chromosome'
bp_col: 'base_pair_location'
ref_col: 'other_allele'
alt_col: 'effect_allele'
p_col: 'p_value'
beta_col: 'beta'
se_col: 'standard_error'
rsid_col: 'rsid'
id_col: 'variant_id'
pretty_isotypes: {"igm": "IgM", "iga": "IgA", "igg": "IgG"}
# NB: some redundancy here to cover alternative names for known loci
epic-iga:
  known_iga_gwas_loci: ["ANKRD55", "IL6ST", "ASCC2|MTMR3", "ATP5PBP6|FILNC1", "CITED2", "CTF1", "DYSF|RPS20P10", "ELL2", "FADS1|FADS2", "GALNT12|NME2P3", "GPATCH2", "HDAC7", "HORMAD2|LIF", "IL1R1", "LINC02655|RPS7P9", "LITAF", "OVOL1|RELA", "POU2AF1", "RUNX2", "RUNX3", "RUNX3|MIR4425", "SH2B3", "ATXN2", "TMEM258", "TNFSF13", "TNFSF15", "TNFSF4|TNFSF18", "TNFSF8", "TRAF3", "ZP3|SSC4D"]
  all: ["RUNX3", "FCGR2B", "TNFSF4", "INAVA", "FADS2", "EFEMP2", "POU2AF1", "HDAC7", "SH2B3", "TRAF3", "LITAF", "CFAP119", "TNFSF13", "TNFRSF13B", "SANBR", "IL1R2", "UQCR10", "ANKRD55", "ELL2", "RUNX2", "PRDM1", "CITED2", "IKZF1", "DTX2", "IRF5", "TNFSF8"]
  novel: ["FCGR2B", "TNFRSF13B|NT5M", "INAVA", "SANBR", "PRDM1", "IKZF1", "IRF5", "TNFSF12|TNFSF13"]
  # Novel and non-novel alike
  iei_genes: ['IL6ST', 'FCGR2B|FCGR3A', "TNFRSF13B", 'POU2AF1', 'TRAF3', 'IKZF1', 'TNFSF13']
imd_traits: ['asthma-ex', 'hyperpara', 'hypothy', 'derm-ecz', 'pbc', 'addi', 'psc', 'ra', 'jia', 'sle', 'crohns', 't1d', 'ms', 'uc-delange', 'liu-decode-lyons-dennis-iga', 'igan']
iga_studies: ['epic', 'liu', 'dennis', 'scepanovic', 'pietzner', 'eldjarn']
igg_studies: ['epic', 'dennis', 'scepanovic', 'pietzner', 'eldjarn']
igm_studies: ['epic', 'scepanovic', 'pietzner', 'eldjarn']
gwas_datasets:
  iga-meta:
    samples: 85204
  igg-meta:
    samples: 58777
  igm-meta:
    samples: 55368
  iga:
    samples: 85204
  igg:
    samples: 58777
  igm:
    samples: 55368
  liu-iga:
    sha256: "44a62f93daa4fc0cecabd144c3b8da1777999787fa8c87a4ca055adf47ecfa51"
    is_gz: False
    url: "https://www.columbiamedicine.org/divisions/kiryluk/gwas/IgA/META.IGA.LEVELS.non-DECODE.txt"
    cases: 0
    controls: 22229
    samples: 22229
    sdY_est: 1.1675795
    rescale: True
    pretty_study: 'Liu et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-08"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: liu-iga.tsv
        data_file_md5sum: b9bc99a0fc6da44d1cb71d75da9a63f5
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  liu-decode-iga:
    sha256: "1ae6806d393eba53ed127af56eb28c8ad08683c7c0abe3baeaba8743b9537c31"
    is_gz: False
    url: "https://www.columbiamedicine.org/divisions/kiryluk/gwas/IgA/META.IGA.LEVELS.ALL.COMBINED.txt"
    cases: 0
    controls: 41448
    samples: 41448
    sdY_est: 1.5899747
    rescale: True
    pretty_study: 'Liu et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-08"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: liu-decode-iga.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  dennis-iga:
    sha256: "9ffc96ec546fb2c886dde9e19ddce7602aaa611d817c8c25360438a000f52315"
    is_gz: True
    url: "https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90012001-GCST90013000/GCST90012678/GCST90012678_buildGRCh37.tsv.gz"
    cases: 0
    controls: 7677
    samples: 7677
    sdY_est: 0.9110791
    rescale: True
    pretty_study: 'Dennis et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: dennis-iga.tsv
        data_file_md5sum: 4cb00f352dc88df8d06d88c62e3d9a4a
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  dennis-igg:
    sha256: "45965d3518c6ebaf85919ae1b6c9c9ce96eed9461406c855ac3b5eec4cef52a8"
    is_gz: True
    url: "https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90012001-GCST90013000/GCST90012679/GCST90012679_buildGRCh37.tsv.gz"
    cases: 0
    controls: 3471
    samples: 3471
    sdY_est: 0.9345117
    rescale: True
    pretty_study: 'Dennis et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: 1-based
        data_file_name: dennis-igg.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  epic-iga:
    sha256: "7c477637437832d323abbc4d947a2097ed6714e2f079b0efa57d428e48e510d6"
    is_gz: True
    url: ""
    cases: 0
    controls: 7938
    samples: 7938
    sdY_est: 0.4996091
    rescale: True
    pretty_study: 'EPIC'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: iga.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  epic-igg:
    sha256: "e2ccea19e475497ad75d0a0cad778b2075092aa4fad7a280b75a1aa7cf0319bb"
    is_gz: True
    url: ""
    cases: 0
    controls: 7946
    samples: 7946
    sdY_est: 0.2871838
    rescale: True
    pretty_study: 'EPIC'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: igg.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  epic-igm:
    sha256: "d24ebe56b8b13a8c8959b6d4c3b942475612e1f3bd7e54ac6e4f35057c4d17b1"
    is_gz: True
    url: ""
    cases: 0
    controls: 8008
    samples: 8008
    sdY_est: 0.5358721
    rescale: True
    pretty_study: 'EPIC'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: igm.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  scepanovic-igg:
    sha256: "b1266d6fa5b46b3e4cb19f6424d1f450791bc8462bedca9229a622a01c5a7251"
    is_gz: True
    url: "https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST006001-GCST007000/GCST006357/harmonised/30053915-GCST006357-EFO_0004565-build37.f.tsv.gz"
    cases: 0
    controls: 1000
    samples: 1000
    sdY_est: 0.0788076
    rescale: True
    pretty_study: 'Scepanovic et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: scepanovic-igg.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  scepanovic-igm:
    sha256: "106b9a4bd11d8a69295568809830060d59c529bed6cb9b4c4b7540c110058d74"
    is_gz: True
    url: "https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST006001-GCST007000/GCST006359/harmonised/30053915-GCST006359-EFO_0004993-build37.f.tsv.gz"
    cases: 0
    controls: 1000
    samples: 1000
    sdY_est: 0.1933939
    rescale: True
    pretty_study: 'Scepanovic et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: scepanovic-igm.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  scepanovic-iga:
    sha256: "997c91148f9e4baf72409f362c77085556a325ed1f6348914a6d7fedc12a96c0"
    is_gz: True
    url: "https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST006001-GCST007000/GCST006360/harmonised/30053915-GCST006360-EFO_0004912-build37.f.tsv.gz"
    cases: 0
    controls: 1000
    samples: 1000
    sdY_est: 0.1712270
    rescale: True
    pretty_study: 'Scepanovic et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: scepanovic-iga.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  pietzner-igm:
    sha256: "2990e135930c095ae5331cf81a751d03de48544a11ca65fd74890ed27f96559f"
    is_gz: True
    url: ""
    cases: 0
    controls: 10708
    samples: 10708
    sdY_est: 0.9821195
    rescale: False
    pretty_study: 'Pietzner et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: pietzner-igm.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  pietzner-iga:
    sha256: "23dfa773c9cd962c379587c46fa6b9b15a71dda00d78e0605bc76381ee195949"
    is_gz: True
    url: ""
    cases: 0
    controls: 10708
    samples: 10708
    sdY_est: 1.0155681
    rescale: False
    pretty_study: 'Pietzner et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: pietzner-iga.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  pietzner-igg:
    sha256: "d83c9564d58b11df13488df3f44b3544c2df2f585b82a62f9363f21537a3e44b"
    is_gz: True
    url: ""
    cases: 0
    controls: 10708
    samples: 10708
    sdY_est: 1.0145151
    rescale: False
    pretty_study: 'Pietzner et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: pietzner-igg.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  gudjonsson-igg:
    sha256: "5d85d5b6efe340cc077f57476eb72554798bfdec7802ed030b3824b5f8574f9a"
    is_gz: True
    url: "https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90088001-GCST90089000/GCST90088489/harmonised/35078996-GCST90088489-EFO_0007937-Build37.f.tsv.gz"
    cases: 0
    controls: 5356
    samples: 5356
    sdY_est: 0.9441563
    rescale: True
    pretty_study: 'Gudjonsson et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: gudjonsson-igg.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  gudjonsson-iga:
    sha256: "3f2eb87f762ef6928e24f1386f7743df213e37b3acd8b3820c61068a6fbbd4eb"
    is_gz: True
    url: "https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90086001-GCST90087000/GCST90086533/harmonised/35078996-GCST90086533-EFO_0007937-Build37.f.tsv.gz"
    cases: 0
    controls: 5358
    samples: 5358
    sdY_est: 0.9342935
    rescale: True
    pretty_study: 'Gudjonsson et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: gudjonsson-iga.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  gudjonsson-igm:
    sha256: "93a91e3fa42f95be0017c6ca1fec07cc3a41b685b21a7b3049a9e5aacf446d44"
    is_gz: True
    url: "https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90088001-GCST90089000/GCST90088220/harmonised/35078996-GCST90088220-EFO_0007937-Build37.f.tsv.gz"
    cases: 0
    controls: 5362
    samples: 5362
    sdY_est: 0.9793915
    rescale: False
    pretty_study: 'Gudjonsson et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: gudjonsson-igm.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  eldjarn-igg:
    sha256: "435830c883ea7beb9af83e5f4f61432b8774584f830159ce62446c1f4dea7973"
    is_gz: True
    url: ""
    cases: 0
    controls: 35652
    samples: 35652
    sdY_est: 1.0449364
    rescale: False
    pretty_study: 'Eldjarn et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: eldjarn-igg.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  eldjarn-iga:
    sha256: "c60bc7bafb35d634a44d9226a067a982977e6a6c956ca6a052403bd2fce47a22"
    is_gz: True
    url: ""
    cases: 0
    controls: 35652
    samples: 35652
    sdY_est: 1.1091828
    rescale: True
    pretty_study: 'Eldjarn et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: eldjarn-iga.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
  eldjarn-igm:
    sha256: "56699a3efa4c377602c76ad7a364bd25630eeb58841df95ac4f025d6c148cc9c"
    is_gz: True
    url: ""
    cases: 0
    controls: 35652
    samples: 35652
    sdY_est: 1.0969310
    rescale: True
    pretty_study: 'Eldjarn et al.'
    gwas_ssf:
        date_metadata_last_modified: "2024-11-11"
        genome_assembly: GRCh37
        coordinate_system: "1-based"
        data_file_name: eldjarn-igm.tsv
        data_file_md5sum: ""
        file_type: "GWAS-SSF v0.1"
        is_harmonised: false
        is_sorted: false
loci:
  igh:
    chrom: 14
    start: 105586437
    stop: 106879844
